username="//input[@name='username']"
password="//input[@name='password']"
submit_button="//button[normalize-space()='login']"
avatar_Element="//span[@class='avatar avatar-medium']"
enrollment_Element="//a[@href='/app/enrollment']"
class_enrollment_Element="//a[@href='/app/class-enrollment']"
enrollment_button="//*[@data-label='Add%20Class%20Enrollment']"
student_fieldname="//*[@data-fieldname='student'][@data-doctype='Class Enrollment']"
student_fieldname_doctype="//*[@data-fieldname='student'][@data-doctype='Class Enrollment']//following::ul[1]//p[@title='STR-2023-00012']"
academic_term="//*[@data-fieldname='academic_term'][@data-doctype='Class Enrollment']"
academic_term_doctype="//*[@data-fieldname='academic_term'][@data-doctype='Class Enrollment']//following::ul[1]//*[text()='2022/202303']"
course_Element="//*[@data-fieldname='course'][@data-doctype='Class Enrollment']"
course_Element_doctyp="//*[@data-fieldname='course'][@data-doctype='Class Enrollment']//following::ul[1]//*[@title='Eng101']"
class_Element="//*[@data-fieldname='class'][@data-doctype='Class Enrollment']"
class_Element_doctyp="//*[@data-fieldname='class'][@data-doctype='Class Enrollment']//following::ul[1]//*[text()='2022/202303-Eng101-lab-088']"
Class_Enrollment="//*[@data-fieldname='course'][@data-doctype='Class Enrollment']"
Class_Enrollment_doctyp="//*[@data-fieldname='course'][@data-doctype='Class Enrollment']//following::ul[1]//*[text()='English, Eng101']"
enrollment_status="//*[@data-fieldname='enrollment_status'][@data-doctype='Class Enrollment']"
Enrolled_status="//*[@data-fieldname='enrollment_status'][@data-doctype='Class Enrollment']//following::ul[1]//*[text()='Enrolled']"
Dropped_status="//*[@data-fieldname='enrollment_status'][@data-doctype='Class Enrollment']//following::ul[1]//*[text()='Dropped']"
checkbox="//input[@data-fieldname='online'][@type='checkbox']"
submmite_forme="//*[@data-label='Save']"
Succfully_submitt="//*[@id='alert-container']"
Error_message="//*[text()='Please fill all the mandatory fields.']"
academic_structure="//span[@class='sidebar-item-label'][normalize-space()='Academic Structure']"
Campus_doctype="//span[normalize-space()='Campuses']"
Campus_button="//span[@data-label='Add%20Campus']"
Edit_full_forme="//div[@class='modal fade show']//button[contains(@class,'btn btn-secondary btn-sm')][normalize-space()='Edit Full Form']"
fill_Campus_forme="//*[@id='page-Campus']/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[2]/div/div/div[2]/div[2]/div/div/form/div[2]/div/div[2]/div[1]/input"
Campus_Code="//*[@id='page-Campus']/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[2]/div/div/div[2]/div[2]/div/div/form/div[3]/div/div[2]/div[1]/input"
Campus_location="//*[@id='page-Campus']/div[2]/div[2]/div/div[3]/div[2]/div[1]/div[2]/div/div/div[2]/div[2]/div/div/form/div[4]/div/div[2]/div[1]/div/div/input"
mass_enrollment_element="//span[normalize-space()='Mass Enrollments']"
New_Mass_Enrollment_button="//span[@data-label='Add%20Mass%20Enrollment']"
Academic_Term_fieldname="//input[@class='input-with-feedback form-control bold']"
Academic_Term_fieldname_doctype="//p[@title='20241']"
Add_Row="//label[normalize-space()='Students List']//following::button[normalize-space()='Add Row'][1]"
select_student="(//div[@data-fieldname='student_id'])[2]"
student_id="//p[@title='S-2023-00199']"
action_fieldname="//select[@type='text' and @data-fieldname='action']"
action="//select[@type='text' and @data-fieldname='action']//option[@value='Add a Class']"
Default_Enrolled_status="//*[@id='page-Mass Enrollment']/div[2]/div[2]/div/div[3]/div/div[1]/div[2]/div/div/div[2]/div[5]/div[2]/div/form/div[2]/div/div[2]/div[1]/div/div/input"
Enrolled_status="//p[@title='Enrolled']"
add_classes="//label[normalize-space()='Classes']//following::button[normalize-space()='Add Row'][1]"
select_class="(//div[@data-fieldname='class'])[2]"
select_class_2="(//div[@data-fieldname='class'])[4]"
class_name="//p[@title='202410-انج 101-1-تمارين / عملي-117']"
class_name_2="//p[@title='202410-انج 101-1-نظري-091']"
select_student="(//input[@class='grid-row-check'])[3]"
click_Run="//button[normalize-space()='Run']"



